site_url: https://kyleh-portfolio.netlify.app/
logo_url: https://kyleh-portfolio.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'site'
    label: 'Site settings'
    files:
      - name: 'info'
        label: 'Info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - {
              label: Site Email,
              name: siteemail,
              widget: string,
              hint: 'Please enter the email you wish users to see on this site.',
              required: false,
            }
          - {
              label: Twitter link,
              name: twitterlink,
              widget: string,
              hint: 'Paste the full URL from your profile page, ex: https://twitter.com/yourAccount',
              required: false,
            }
          - {
              label: Instagram link,
              name: instalink,
              widget: string,
              hint: 'Paste the full URL from your profile page, ex: https://instagram.com/yourAccount',
              required: false,
            }
          - {
              label: YouTube link,
              name: youtubelink,
              widget: string,
              hint: 'Paste the full URL from your profile page, ex: https://youtube.com/yourAccount',
              required: false,
            }
          - {
              label: LinkedIn link,
              name: linkedinlink,
              widget: string,
              hint: 'Paste the full URL from your profile page, ex: https://linkedin.com/yourAccount',
              required: false,
            }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          hint: 'Using one or two sentances, provide a sample of the post.',
          required: false,
        }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'image',
          hint: 'Images sized 1200px x 800px work best.',
          required: false,
          allow_multiple: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Project Category',
          name: 'category',
          widget: 'select',
          default: 'writing',
          options: [{ label: 'Writing', value: 'writing' }, { label: 'Multimedia', value: 'multimedia' }],
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'string',
          hint: 'Using one or two sentances, provide a sample of the post.',
          required: false,
        }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'image',
          hint: 'Images sized 1200px x 800px work best.',
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Video Cover',
          name: 'videolink',
          widget: 'string',
          required: false,
          hint: 'ONLY PASTE THE END OF THE URL, ex: https://youtube.com/embed/_____',
        }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
